### ISSUE TITLE
404 Error when using with Laravel Modules

### ISSUE THREAD

**Issue by alwinaugustin** [YaroslavFedan/modules-inertia#3]
I have used it like this in the `app.js`

```
createInertiaApp({

    title: (title) => `${ title } - ${ appName }`,
    resolve: (name) => {
        let isModule = name.split("::");
        console.log(isModule);
        if (isModule.length > 1) {
            let module = isModule[0];
            let pathTo = isModule[1];
            resolvePageComponent(`../../Modules/Dashboard/Resources/Pages/Index.vue`, import.meta.glob('../../Modules/Dashboard/Resources/Pages/*.vue'))
        } else {
            resolvePageComponent(`./Pages/${ name }.vue`, import.meta.glob('./Pages/**/*.vue'))
        }
    },
    setup({ el, App, props, plugin }) {
        return createApp({ render: () => h(App, props) })
            .use(plugin)
            .use(ZiggyVue, Ziggy)
            .mount(el);
    },
    progress: {
        color: '#4B5563',
    },
});
```

I have just given the direct path for testing. Also I have used `resolvePageComponent` as when I use `require`, it was showing an error which says `require is not defined`. 

I have my module in `Module/Dashbaord` and everything is working without the Inertia. Now when I access the page, I am getting a blank page and I have the following errors in the dev tools console. 

﻿
```
dashboard:19 
 GET http://127.0.0.1:5173/resources/js/Pages/Dashboard::Resources/Pages/Index.vue net::ERR_ABORTED 404 (Not Found)
```
```
createInertiaApp.ts:34 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'default')
    at createInertiaApp.ts:34:93
    at async E (createInertiaApp.ts:38:18)
```

It will be very much helpful if you can help me to resolve these errors.

**Comment by hareom284** [comment]
@alwinaugustin  You can change your render like this    
### In the controller, you  can pass the value 
![carbon](https://user-images.githubusercontent.com/64596861/224781850-507cbc23-f072-465a-a7aa-bd26c6c758fb.png)

### In the resources/js/app.js you need to configure it like this 
![carbon (1)](https://user-images.githubusercontent.com/64596861/224782072-ed18e629-01d5-4d1d-8b21-b5ced7ceb94d.png)

**You need to pass the correct file path and module name and file path from the Controller. I hope this will help you**
